//! The packaged country flags, and the texture cache that draws them.
//!
//! Generated by `tools/gen_flags.py` — edit the DXCC table in
//! `sdroxide-types/src/entity_flags.rs` and re-run it rather than editing the
//! list below. The images are public domain; see `assets/flags/README.md`.
//!
//! They are compiled in rather than fetched: a decode list that only shows
//! where stations are once the network answers is a decode list that shows it
//! differently on every machine, and the remote client has no business
//! reaching past sdroxide to a third-party CDN.

use std::collections::HashMap;

use eframe::egui;

/// Every flag we ship, keyed by the code [`sdroxide_types::EntityInfo::flag`]
/// carries. Sorted, so the lookup can binary-search.
static FLAG_PNG: &[(&str, &[u8])] = &[
    ("AC", include_bytes!("../assets/flags/AC.png")),
    ("AD", include_bytes!("../assets/flags/AD.png")),
    ("AE", include_bytes!("../assets/flags/AE.png")),
    ("AF", include_bytes!("../assets/flags/AF.png")),
    ("AG", include_bytes!("../assets/flags/AG.png")),
    ("AI", include_bytes!("../assets/flags/AI.png")),
    ("AL", include_bytes!("../assets/flags/AL.png")),
    ("AM", include_bytes!("../assets/flags/AM.png")),
    ("AO", include_bytes!("../assets/flags/AO.png")),
    ("AQ", include_bytes!("../assets/flags/AQ.png")),
    ("AR", include_bytes!("../assets/flags/AR.png")),
    ("AS", include_bytes!("../assets/flags/AS.png")),
    ("AT", include_bytes!("../assets/flags/AT.png")),
    ("AU", include_bytes!("../assets/flags/AU.png")),
    ("AU-TAS", include_bytes!("../assets/flags/AU-TAS.png")),
    ("AW", include_bytes!("../assets/flags/AW.png")),
    ("AX", include_bytes!("../assets/flags/AX.png")),
    ("AZ", include_bytes!("../assets/flags/AZ.png")),
    ("BA", include_bytes!("../assets/flags/BA.png")),
    ("BB", include_bytes!("../assets/flags/BB.png")),
    ("BD", include_bytes!("../assets/flags/BD.png")),
    ("BE", include_bytes!("../assets/flags/BE.png")),
    ("BF", include_bytes!("../assets/flags/BF.png")),
    ("BG", include_bytes!("../assets/flags/BG.png")),
    ("BH", include_bytes!("../assets/flags/BH.png")),
    ("BI", include_bytes!("../assets/flags/BI.png")),
    ("BJ", include_bytes!("../assets/flags/BJ.png")),
    ("BL", include_bytes!("../assets/flags/BL.png")),
    ("BM", include_bytes!("../assets/flags/BM.png")),
    ("BN", include_bytes!("../assets/flags/BN.png")),
    ("BO", include_bytes!("../assets/flags/BO.png")),
    ("BQ", include_bytes!("../assets/flags/BQ.png")),
    ("BR", include_bytes!("../assets/flags/BR.png")),
    ("BS", include_bytes!("../assets/flags/BS.png")),
    ("BT", include_bytes!("../assets/flags/BT.png")),
    ("BV", include_bytes!("../assets/flags/BV.png")),
    ("BW", include_bytes!("../assets/flags/BW.png")),
    ("BY", include_bytes!("../assets/flags/BY.png")),
    ("BZ", include_bytes!("../assets/flags/BZ.png")),
    ("CA", include_bytes!("../assets/flags/CA.png")),
    ("CC", include_bytes!("../assets/flags/CC.png")),
    ("CD", include_bytes!("../assets/flags/CD.png")),
    ("CF", include_bytes!("../assets/flags/CF.png")),
    ("CG", include_bytes!("../assets/flags/CG.png")),
    ("CH", include_bytes!("../assets/flags/CH.png")),
    ("CI", include_bytes!("../assets/flags/CI.png")),
    ("CK", include_bytes!("../assets/flags/CK.png")),
    ("CL", include_bytes!("../assets/flags/CL.png")),
    ("CM", include_bytes!("../assets/flags/CM.png")),
    ("CN", include_bytes!("../assets/flags/CN.png")),
    ("CO", include_bytes!("../assets/flags/CO.png")),
    ("CO-SAP", include_bytes!("../assets/flags/CO-SAP.png")),
    ("CP", include_bytes!("../assets/flags/CP.png")),
    ("CR", include_bytes!("../assets/flags/CR.png")),
    ("CU", include_bytes!("../assets/flags/CU.png")),
    ("CV", include_bytes!("../assets/flags/CV.png")),
    ("CW", include_bytes!("../assets/flags/CW.png")),
    ("CX", include_bytes!("../assets/flags/CX.png")),
    ("CY", include_bytes!("../assets/flags/CY.png")),
    ("CZ", include_bytes!("../assets/flags/CZ.png")),
    ("DE", include_bytes!("../assets/flags/DE.png")),
    ("DJ", include_bytes!("../assets/flags/DJ.png")),
    ("DK", include_bytes!("../assets/flags/DK.png")),
    ("DM", include_bytes!("../assets/flags/DM.png")),
    ("DO", include_bytes!("../assets/flags/DO.png")),
    ("DZ", include_bytes!("../assets/flags/DZ.png")),
    ("EC", include_bytes!("../assets/flags/EC.png")),
    ("EE", include_bytes!("../assets/flags/EE.png")),
    ("EG", include_bytes!("../assets/flags/EG.png")),
    ("EH", include_bytes!("../assets/flags/EH.png")),
    ("ER", include_bytes!("../assets/flags/ER.png")),
    ("ES", include_bytes!("../assets/flags/ES.png")),
    ("ES-CE", include_bytes!("../assets/flags/ES-CE.png")),
    ("ES-CN", include_bytes!("../assets/flags/ES-CN.png")),
    ("ES-IB", include_bytes!("../assets/flags/ES-IB.png")),
    ("ET", include_bytes!("../assets/flags/ET.png")),
    ("FI", include_bytes!("../assets/flags/FI.png")),
    ("FJ", include_bytes!("../assets/flags/FJ.png")),
    ("FK", include_bytes!("../assets/flags/FK.png")),
    ("FM", include_bytes!("../assets/flags/FM.png")),
    ("FO", include_bytes!("../assets/flags/FO.png")),
    ("FR", include_bytes!("../assets/flags/FR.png")),
    ("GA", include_bytes!("../assets/flags/GA.png")),
    ("GB", include_bytes!("../assets/flags/GB.png")),
    ("GB-ENG", include_bytes!("../assets/flags/GB-ENG.png")),
    ("GB-NIR", include_bytes!("../assets/flags/GB-NIR.png")),
    ("GB-SCT", include_bytes!("../assets/flags/GB-SCT.png")),
    ("GB-WLS", include_bytes!("../assets/flags/GB-WLS.png")),
    ("GD", include_bytes!("../assets/flags/GD.png")),
    ("GE", include_bytes!("../assets/flags/GE.png")),
    ("GF", include_bytes!("../assets/flags/GF.png")),
    ("GG", include_bytes!("../assets/flags/GG.png")),
    ("GH", include_bytes!("../assets/flags/GH.png")),
    ("GI", include_bytes!("../assets/flags/GI.png")),
    ("GL", include_bytes!("../assets/flags/GL.png")),
    ("GM", include_bytes!("../assets/flags/GM.png")),
    ("GN", include_bytes!("../assets/flags/GN.png")),
    ("GP", include_bytes!("../assets/flags/GP.png")),
    ("GQ", include_bytes!("../assets/flags/GQ.png")),
    ("GR", include_bytes!("../assets/flags/GR.png")),
    ("GS", include_bytes!("../assets/flags/GS.png")),
    ("GT", include_bytes!("../assets/flags/GT.png")),
    ("GU", include_bytes!("../assets/flags/GU.png")),
    ("GW", include_bytes!("../assets/flags/GW.png")),
    ("GY", include_bytes!("../assets/flags/GY.png")),
    ("HK", include_bytes!("../assets/flags/HK.png")),
    ("HM", include_bytes!("../assets/flags/HM.png")),
    ("HN", include_bytes!("../assets/flags/HN.png")),
    ("HR", include_bytes!("../assets/flags/HR.png")),
    ("HT", include_bytes!("../assets/flags/HT.png")),
    ("HU", include_bytes!("../assets/flags/HU.png")),
    ("ID", include_bytes!("../assets/flags/ID.png")),
    ("IE", include_bytes!("../assets/flags/IE.png")),
    ("IL", include_bytes!("../assets/flags/IL.png")),
    ("IM", include_bytes!("../assets/flags/IM.png")),
    ("IN", include_bytes!("../assets/flags/IN.png")),
    ("IO", include_bytes!("../assets/flags/IO.png")),
    ("IQ", include_bytes!("../assets/flags/IQ.png")),
    ("IR", include_bytes!("../assets/flags/IR.png")),
    ("IS", include_bytes!("../assets/flags/IS.png")),
    ("IT", include_bytes!("../assets/flags/IT.png")),
    ("JE", include_bytes!("../assets/flags/JE.png")),
    ("JM", include_bytes!("../assets/flags/JM.png")),
    ("JO", include_bytes!("../assets/flags/JO.png")),
    ("JP", include_bytes!("../assets/flags/JP.png")),
    ("KE", include_bytes!("../assets/flags/KE.png")),
    ("KG", include_bytes!("../assets/flags/KG.png")),
    ("KH", include_bytes!("../assets/flags/KH.png")),
    ("KI", include_bytes!("../assets/flags/KI.png")),
    ("KM", include_bytes!("../assets/flags/KM.png")),
    ("KN", include_bytes!("../assets/flags/KN.png")),
    ("KP", include_bytes!("../assets/flags/KP.png")),
    ("KR", include_bytes!("../assets/flags/KR.png")),
    ("KW", include_bytes!("../assets/flags/KW.png")),
    ("KY", include_bytes!("../assets/flags/KY.png")),
    ("KZ", include_bytes!("../assets/flags/KZ.png")),
    ("LA", include_bytes!("../assets/flags/LA.png")),
    ("LB", include_bytes!("../assets/flags/LB.png")),
    ("LC", include_bytes!("../assets/flags/LC.png")),
    ("LI", include_bytes!("../assets/flags/LI.png")),
    ("LK", include_bytes!("../assets/flags/LK.png")),
    ("LR", include_bytes!("../assets/flags/LR.png")),
    ("LS", include_bytes!("../assets/flags/LS.png")),
    ("LT", include_bytes!("../assets/flags/LT.png")),
    ("LU", include_bytes!("../assets/flags/LU.png")),
    ("LV", include_bytes!("../assets/flags/LV.png")),
    ("LY", include_bytes!("../assets/flags/LY.png")),
    ("MA", include_bytes!("../assets/flags/MA.png")),
    ("MC", include_bytes!("../assets/flags/MC.png")),
    ("MD", include_bytes!("../assets/flags/MD.png")),
    ("ME", include_bytes!("../assets/flags/ME.png")),
    ("MF", include_bytes!("../assets/flags/MF.png")),
    ("MG", include_bytes!("../assets/flags/MG.png")),
    ("MH", include_bytes!("../assets/flags/MH.png")),
    ("MK", include_bytes!("../assets/flags/MK.png")),
    ("ML", include_bytes!("../assets/flags/ML.png")),
    ("MM", include_bytes!("../assets/flags/MM.png")),
    ("MN", include_bytes!("../assets/flags/MN.png")),
    ("MO", include_bytes!("../assets/flags/MO.png")),
    ("MP", include_bytes!("../assets/flags/MP.png")),
    ("MQ", include_bytes!("../assets/flags/MQ.png")),
    ("MR", include_bytes!("../assets/flags/MR.png")),
    ("MS", include_bytes!("../assets/flags/MS.png")),
    ("MT", include_bytes!("../assets/flags/MT.png")),
    ("MU", include_bytes!("../assets/flags/MU.png")),
    ("MV", include_bytes!("../assets/flags/MV.png")),
    ("MW", include_bytes!("../assets/flags/MW.png")),
    ("MX", include_bytes!("../assets/flags/MX.png")),
    ("MY", include_bytes!("../assets/flags/MY.png")),
    ("MZ", include_bytes!("../assets/flags/MZ.png")),
    ("NA", include_bytes!("../assets/flags/NA.png")),
    ("NC", include_bytes!("../assets/flags/NC.png")),
    ("NE", include_bytes!("../assets/flags/NE.png")),
    ("NF", include_bytes!("../assets/flags/NF.png")),
    ("NG", include_bytes!("../assets/flags/NG.png")),
    ("NI", include_bytes!("../assets/flags/NI.png")),
    ("NL", include_bytes!("../assets/flags/NL.png")),
    ("NO", include_bytes!("../assets/flags/NO.png")),
    ("NP", include_bytes!("../assets/flags/NP.png")),
    ("NR", include_bytes!("../assets/flags/NR.png")),
    ("NU", include_bytes!("../assets/flags/NU.png")),
    ("NZ", include_bytes!("../assets/flags/NZ.png")),
    ("OM", include_bytes!("../assets/flags/OM.png")),
    ("PA", include_bytes!("../assets/flags/PA.png")),
    ("PE", include_bytes!("../assets/flags/PE.png")),
    ("PF", include_bytes!("../assets/flags/PF.png")),
    ("PG", include_bytes!("../assets/flags/PG.png")),
    ("PH", include_bytes!("../assets/flags/PH.png")),
    ("PK", include_bytes!("../assets/flags/PK.png")),
    ("PL", include_bytes!("../assets/flags/PL.png")),
    ("PM", include_bytes!("../assets/flags/PM.png")),
    ("PN", include_bytes!("../assets/flags/PN.png")),
    ("PR", include_bytes!("../assets/flags/PR.png")),
    ("PS", include_bytes!("../assets/flags/PS.png")),
    ("PT", include_bytes!("../assets/flags/PT.png")),
    ("PW", include_bytes!("../assets/flags/PW.png")),
    ("PY", include_bytes!("../assets/flags/PY.png")),
    ("QA", include_bytes!("../assets/flags/QA.png")),
    ("RE", include_bytes!("../assets/flags/RE.png")),
    ("RO", include_bytes!("../assets/flags/RO.png")),
    ("RS", include_bytes!("../assets/flags/RS.png")),
    ("RU", include_bytes!("../assets/flags/RU.png")),
    ("RW", include_bytes!("../assets/flags/RW.png")),
    ("SA", include_bytes!("../assets/flags/SA.png")),
    ("SB", include_bytes!("../assets/flags/SB.png")),
    ("SC", include_bytes!("../assets/flags/SC.png")),
    ("SD", include_bytes!("../assets/flags/SD.png")),
    ("SE", include_bytes!("../assets/flags/SE.png")),
    ("SG", include_bytes!("../assets/flags/SG.png")),
    ("SH", include_bytes!("../assets/flags/SH.png")),
    ("SI", include_bytes!("../assets/flags/SI.png")),
    ("SJ", include_bytes!("../assets/flags/SJ.png")),
    ("SK", include_bytes!("../assets/flags/SK.png")),
    ("SL", include_bytes!("../assets/flags/SL.png")),
    ("SM", include_bytes!("../assets/flags/SM.png")),
    ("SN", include_bytes!("../assets/flags/SN.png")),
    ("SO", include_bytes!("../assets/flags/SO.png")),
    ("SR", include_bytes!("../assets/flags/SR.png")),
    ("SS", include_bytes!("../assets/flags/SS.png")),
    ("ST", include_bytes!("../assets/flags/ST.png")),
    ("SV", include_bytes!("../assets/flags/SV.png")),
    ("SX", include_bytes!("../assets/flags/SX.png")),
    ("SY", include_bytes!("../assets/flags/SY.png")),
    ("SZ", include_bytes!("../assets/flags/SZ.png")),
    ("TA", include_bytes!("../assets/flags/TA.png")),
    ("TC", include_bytes!("../assets/flags/TC.png")),
    ("TD", include_bytes!("../assets/flags/TD.png")),
    ("TF", include_bytes!("../assets/flags/TF.png")),
    ("TG", include_bytes!("../assets/flags/TG.png")),
    ("TH", include_bytes!("../assets/flags/TH.png")),
    ("TJ", include_bytes!("../assets/flags/TJ.png")),
    ("TK", include_bytes!("../assets/flags/TK.png")),
    ("TL", include_bytes!("../assets/flags/TL.png")),
    ("TM", include_bytes!("../assets/flags/TM.png")),
    ("TN", include_bytes!("../assets/flags/TN.png")),
    ("TO", include_bytes!("../assets/flags/TO.png")),
    ("TR", include_bytes!("../assets/flags/TR.png")),
    ("TT", include_bytes!("../assets/flags/TT.png")),
    ("TV", include_bytes!("../assets/flags/TV.png")),
    ("TW", include_bytes!("../assets/flags/TW.png")),
    ("TZ", include_bytes!("../assets/flags/TZ.png")),
    ("UA", include_bytes!("../assets/flags/UA.png")),
    ("UG", include_bytes!("../assets/flags/UG.png")),
    ("UM", include_bytes!("../assets/flags/UM.png")),
    ("UN", include_bytes!("../assets/flags/UN.png")),
    ("US", include_bytes!("../assets/flags/US.png")),
    ("US-AK", include_bytes!("../assets/flags/US-AK.png")),
    ("US-HI", include_bytes!("../assets/flags/US-HI.png")),
    ("UY", include_bytes!("../assets/flags/UY.png")),
    ("UZ", include_bytes!("../assets/flags/UZ.png")),
    ("VA", include_bytes!("../assets/flags/VA.png")),
    ("VC", include_bytes!("../assets/flags/VC.png")),
    ("VE", include_bytes!("../assets/flags/VE.png")),
    ("VG", include_bytes!("../assets/flags/VG.png")),
    ("VI", include_bytes!("../assets/flags/VI.png")),
    ("VN", include_bytes!("../assets/flags/VN.png")),
    ("VU", include_bytes!("../assets/flags/VU.png")),
    ("WF", include_bytes!("../assets/flags/WF.png")),
    ("WS", include_bytes!("../assets/flags/WS.png")),
    ("XK", include_bytes!("../assets/flags/XK.png")),
    ("YE", include_bytes!("../assets/flags/YE.png")),
    ("YT", include_bytes!("../assets/flags/YT.png")),
    ("ZA", include_bytes!("../assets/flags/ZA.png")),
    ("ZM", include_bytes!("../assets/flags/ZM.png")),
    ("ZW", include_bytes!("../assets/flags/ZW.png")),
];

/// Decoded flag textures, filled the first time each flag is drawn.
///
/// One entry per *code*, not per decode: a band full of German stations
/// uploads one 48×32 texture between them. Entries stay for the life of the
/// process — the whole set decoded at once is well under a megabyte of VRAM,
/// and a band opening is exactly when re-decoding would cost the most.
#[derive(Default)]
pub struct Flags {
    /// `None` marks a code whose PNG failed to decode, so we try it once.
    cache: HashMap<&'static str, Option<egui::TextureHandle>>,
}

impl Flags {
    /// The texture for a flag code, decoding and uploading it on first use.
    fn texture(&mut self, ctx: &egui::Context, code: &str) -> Option<&egui::TextureHandle> {
        let i = FLAG_PNG.binary_search_by(|(c, _)| (*c).cmp(code)).ok()?;
        let (code, png) = FLAG_PNG[i];
        self.cache
            .entry(code)
            .or_insert_with(|| {
                let img = image::load_from_memory_with_format(png, image::ImageFormat::Png).ok()?;
                let rgba = img.to_rgba8();
                let (w, h) = rgba.dimensions();
                let ci = egui::ColorImage::from_rgba_unmultiplied(
                    [w as usize, h as usize],
                    rgba.as_raw(),
                );
                // Linear, and no mipmaps: these are drawn a shade smaller than
                // they are stored, which is the one case nearest sampling
                // turns into ragged stripes.
                Some(ctx.load_texture(format!("flag-{code}"), ci, egui::TextureOptions::LINEAR))
            })
            .as_ref()
    }

    /// Draw a flag no taller than `h` points and no wider than `1.6 * h`,
    /// keeping its own proportions, and report the box it filled.
    ///
    /// Returns `None` when there is no flag for the code — the caller decides
    /// what to put in the gap, which is usually nothing.
    pub fn show(&mut self, ui: &mut egui::Ui, code: &str, h: f32) -> Option<egui::Response> {
        let tex = self.texture(ui.ctx(), code)?;
        let [tw, th] = tex.size();
        let (tw, th) = (tw as f32, th as f32);
        // Fit inside the box rather than stretching to it: flags run from 1:1
        // (Switzerland) to 1:2 (Qatar), and a stretched one reads as wrong
        // even to somebody who could not name it.
        let scale = (h / th).min((h * 1.6) / tw);
        let size = egui::vec2(tw * scale, th * scale);
        let img = egui::Image::new((tex.id(), size)).fit_to_exact_size(size);
        Some(ui.add(img))
    }
}

/// The Jolly Roger a reception the listener marked as a **pirate broadcast**
/// wears in the log.
///
/// Painted rather than shipped as an image or typed as a glyph: it is a dozen
/// shapes at row size, the emblem is the whole of the recognition, and a font
/// is not to be counted on for a symbol. Black cloth inside a light outline, so
/// the flag reads on a dark row and a light one alike — the skull is white on
/// the cloth, and the cloth is outlined so it does not vanish into a dark theme.
pub fn pirate(ui: &mut egui::Ui, h: f32) -> egui::Response {
    let (rect, resp) = ui.allocate_exact_size(egui::vec2(h * 1.2, h), egui::Sense::hover());
    let tip = "Pirate transmission — an unlicensed broadcast";
    if !ui.is_rect_visible(rect) {
        return resp.on_hover_text(tip);
    }
    let p = ui.painter();
    let cloth = egui::Color32::from_rgb(18, 18, 22);
    let white = egui::Color32::from_gray(240);
    p.rect(
        rect.shrink(0.5),
        egui::CornerRadius::ZERO,
        cloth,
        egui::Stroke::new(1.0, egui::Color32::from_gray(170)),
        egui::StrokeKind::Inside,
    );
    let c = rect.center();
    // Skull above the bones; both flattened a little, which is what the emblem
    // is, and what tells it from a plain spot at this size.
    let bone = egui::Stroke::new((h * 0.08).max(1.0), white);
    let d = h * 0.32;
    let by = c.y + h * 0.15;
    p.line_segment(
        [egui::pos2(c.x - d, by - h * 0.08), egui::pos2(c.x + d, by + h * 0.08)],
        bone,
    );
    p.line_segment(
        [egui::pos2(c.x - d, by + h * 0.08), egui::pos2(c.x + d, by - h * 0.08)],
        bone,
    );
    let head = c.y - h * 0.16;
    p.circle_filled(egui::pos2(c.x, head), h * 0.22, white);
    let eye = h * 0.055;
    p.circle_filled(egui::pos2(c.x - h * 0.075, head), eye, cloth);
    p.circle_filled(egui::pos2(c.x + h * 0.075, head), eye, cloth);
    resp.on_hover_text(tip)
}
